/**
 * Legal copy, lifted verbatim from the original static pages.
 *
 * `body` is trusted first-party HTML (headings and paragraphs only) and is
 * injected by the LegalArticle component. The contact block that used to sit
 * at the end of each page is now rendered from SITE so the address and phone
 * number stay in one place.
 */
export const LEGAL_PAGES = {
  "privacy-policy": {
    "title": "Privacy Policy",
    "intro": "Internet Cable N TV is operated by Fico Tech LLC, an independent reseller. We care about your privacy. This policy explains what we collect, how we use it, and the choices you have.",
    "body": "<h2>1. What We Collect</h2><p>Information you give us: When you fill out a form or call us, we may collect your name, phone number, email, service address, ZIP code, and anything else you choose to share.</p><p>Information we collect automatically: When you visit the site, we gather basic technical details like your IP address, browser type, device, and the pages you view.</p><p>Call recording: Calls with us may be recorded for quality and training. By calling us, you agree to this.</p><p>Cookies &amp; tracking: We use cookies and analytics tools to understand how the site is used and improve it. You can turn cookies off in your browser anytime.</p><h2>2. How We Use It</h2><p>We use your information to show available internet, fiber, wireless, and TV options; connect your request to the right provider; contact you about services you asked about; improve the site; and meet legal requirements.</p><h2>3. How We Share It</h2><p>Fico Tech LLC is an independent reseller and does not provide services directly. We do not sell or rent your personal information.</p><p>We may share information with leading providers and carriers, analytics tools, authorized partners when needed to handle your request, and legal authorities if required by law.</p><h2>4. Calls &amp; Texts</h2><p>By giving us your number, you agree we and our partners may contact you by call, text, or automated technology about available plans. Consent is not required to buy anything. Message and data rates may apply. You can opt out anytime by replying STOP or contacting us.</p><h2>5. How Long We Keep It</h2><p>We keep your information only as long as needed to help you, meet legal obligations, and resolve disputes. After that, it is securely deleted or anonymized.</p><h2>6. Your Choices</h2><p>You can ask us to show, correct, or delete your data, unsubscribe from marketing, or opt out of sale/sharing of your data by emailing info@internetcablentv.com.</p><h2>7. Children&#x27;s Privacy</h2><p>This site is not meant for children under 13, and we do not knowingly collect their information.</p><h2>8. Security</h2><p>We use reasonable protections such as SSL encryption. No online method is 100% secure.</p><h2>9. Other Websites</h2><p>Our site may link to other websites. We are not responsible for their privacy practices.</p><h2>10. Updates</h2><p>We may update this policy from time to time and will post changes here.</p>"
  },
  "terms-and-conditions": {
    "title": "Terms and Conditions",
    "intro": "By using this website, you agree to these terms. If you do not agree, please do not use the site.",
    "body": "<h2>1. About Us</h2><p>Internet Cable N TV is operated by Fico Tech LLC, an independent reseller that helps you compare and connect with home internet, fiber, wireless, and TV bundle plans. We do not own any network. All services are provided, installed, and billed by the provider you choose.</p><h2>2. Who Can Use This Site</h2><p>You need to be at least 18, or have a parent or guardian’s permission, to use this site.</p><h2>3. Using the Site</h2><p>Please use the site lawfully. Do not submit anything that breaks the law or infringes on someone else’s rights.</p><h2>4. Billing &amp; Payment</h2><p>All billing is handled by the provider you choose. Fico Tech LLC does not process payments. Billing questions or cancellations should go directly to your provider.</p><h2>5. Privacy</h2><p>Your use of the site is also covered by our Privacy Policy.</p><h2>6. Our Content</h2><p>The text, graphics, and logos on this site belong to Fico Tech LLC or its licensors. Please do not copy or reuse them without permission.</p><h2>7. Installation &amp; Equipment</h2><p>Your chosen provider handles all installation and equipment. Terms and fees vary by provider.</p><h2>8. Liability</h2><p>Fico Tech LLC is not liable for indirect or consequential damages from using this site or services arranged through it. Service delivery, billing, and technical issues are the responsibility of your provider.</p><h2>9. Ending Access</h2><p>We can suspend or end your access to the site if these terms are broken.</p><h2>10. Changes</h2><p>We may update these terms anytime. Continued use of the site means you accept the updates.</p><h2>11. Governing Law</h2><p>These Terms are governed by the laws of the State of Wyoming. Any disputes will be handled in the state or federal courts of Sheridan County, Wyoming.</p>"
  },
  "refund-policy": {
    "title": "Billing and Refund Policy",
    "intro": "Internet Cable N TV is operated by Fico Tech LLC, an independent reseller. We do not provide, install, or bill for any services.",
    "body": "<h2>How Billing Works</h2><p>All billing is handled directly by the provider you choose.</p><h2>Refunds &amp; Billing Questions</h2><p>Since your provider handles all billing, refund requests, billing questions, or cancellations need to go directly to them. We cannot process refunds on a provider’s behalf.</p><h2>We’re Happy to Help Point You in the Right Direction</h2><p>If you are not sure who to contact at your provider, reach out: info@internetcablentv.com · (888) 238-0951</p><h2>Updates</h2><p>We may update this policy from time to time and will post changes here.</p>"
  },
  "disclaimer": {
    "title": "Disclaimer",
    "intro": "Internet Cable N TV is operated by Fico Tech LLC, an independent reseller. This is not the official website of any internet, TV, or wireless service provider.",
    "body": "<h2>We Don&#x27;t Provide the Service</h2><p>Fico Tech LLC does not own, operate, or maintain any network infrastructure, and we are not a licensed service provider. We help you compare and connect with options. All services are provided, installed, and billed by licensed third-party providers.</p><h2>About Provider Logos</h2><p>Any provider logos, trademarks, or brand names shown on this site belong to their respective owners and are used only to identify plans we help you compare. Showing them does not mean Fico Tech LLC owns or operates those services.</p><h2>Pricing &amp; Availability</h2><p>Pricing, speeds, and plan details come from the providers and can change. Availability depends on your location. Final details are confirmed with your chosen provider before you sign up.</p><h2>No Guarantees</h2><p>Everything on this site is provided for general information only. Using this site is at your own risk.</p><h2>Where Responsibility Sits</h2><p>Your provider is responsible for service delivery, network performance, installation, billing, and technical support.</p>"
  },
  "cookie-policy": {
    "title": "Cookie Policy",
    "intro": "Cookies are small files saved on your device when you visit a website. They help us see how the site is used and make it better for you.",
    "body": "<h2>Cookies We Use</h2><p>Analytics cookies help us understand site usage. Advertising/tag tools help manage tracking and measure campaigns. Functional cookies remember preferences so the site works smoothly.</p><h2>Managing Cookies</h2><p>You can control or turn off cookies in your browser settings. Some features may not work as well if you do.</p><h2>Third-Party Cookies</h2><p>Some cookies come from third-party services. We do not control those — check their privacy policies for details.</p><h2>Updates</h2><p>We may update this policy anytime and will post changes here.</p>"
  },
  "reseller-disclosure": {
    "title": "Reseller Disclosure",
    "intro": "Internet Cable N TV is operated by Fico Tech LLC, an independent reseller. We help you compare, choose, and connect with home internet, fiber, wireless, and TV bundle services across the U.S.",
    "body": "<h2>Independent Reseller</h2><p>We are not owned or controlled by any provider or carrier. All services are delivered, installed, billed, and supported by the licensed providers themselves.</p><h2>Compensation</h2><p>We may earn a commission or referral fee from a provider when you sign up for a qualifying service through us. This never changes your price.</p><h2>Plan Details</h2><p>All plan info, including pricing and availability, comes from the providers and can vary by area. Confirm final details with your chosen provider before signing up.</p>"
  },
  "tcpa-consent": {
    "title": "TCPA Consent",
    "intro": "When you submit a form on this site or call us, you agree to let Fico Tech LLC and our authorized partners contact you about home internet, fiber, wireless, and TV bundle options in your area.",
    "body": "<h2>How We May Contact You</h2><p>Contact may come by phone call, text, prerecorded message, or automated technology. Message and data rates may apply. You do not have to agree to this to make a purchase.</p><h2>Opting Out</h2><p>You can opt out anytime by replying STOP to any text, emailing info@internetcablentv.com with “Opt Out” in the subject, or calling (888) 238-0951 and asking to be removed.</p><h2>Processing Time</h2><p>We will process opt-out requests within 10 business days.</p>"
  },
  "do-not-sell-my-info": {
    "title": "Do Not Sell My Personal Information",
    "intro": "Fico Tech LLC does not sell personal information in the traditional sense. If you want to opt out of certain sharing used for cross-context behavioral advertising, contact us.",
    "body": "<h2>Your Request</h2><p>Email info@internetcablentv.com with the subject line “Do Not Sell My Info Request,” or call (888) 238-0951. We will handle verified requests within 45 days.</p><h2>More Information</h2><p>For more on how we use your data, see our Privacy Policy.</p>"
  }
};
